# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'deel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for deel

  target 'deel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'deelTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'deel-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for deel-tvOS

  target 'deel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
